config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients, only:[:index, :show, :edit, :update]
  resources :users
  resources :recipes
  resources :recipe_categories, only:[:new, :create, :destroy]
  resources :subsection_ingredients, only:[:destroy]
  resources :subsections, only:[:destroy]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true
  has_many :subsections, dependent: :destroy
  has_many :subsection_ingredients, through: :subsections, dependent: :destroy
  has_many :ingredients, through: :subsection_ingredients
  has_many :categories, through: :recipe_categories
  has_many :recipe_categories

  validates :name, length: {minimum: 3, maximum: 30}
  validates :description, length: {minimum: 3, maximum: 1500}
  validates :amount, numericality: {greater_than_or_equal_to: 1, only_integer: true}
  validates :duration, numericality: {greater_than_or_equal_to: 1}

  def duration_to_s
    hh, mm = duration.divmod(60)

    s = "#{hh} hours #{mm} mins"
    s = "#{hh} hours" if mm == 0
    s = "#{mm} mins" if hh == 0
    s
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_units, only: [:new, :edit, :create]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_recipe_user_is_current_user, only: [:edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    order = params[:order] || 'name'
    @recipes = case order
                 when 'name' then
                   Recipe.order(:name)
                 when 'added' then
                   Recipe.order(created_at: :desc)
               end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    session[:recipe_id] = @recipe.id
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    hours = params.require(:data).permit(:time_h)[:time_h].to_i
    mins = params.require(:data).permit(:time_min)[:time_min].to_i
    @recipe.duration = hours * 60 + mins
    @recipe.user = current_user

    if request.xhr?
      everything_valid = @recipe.valid?

      returned = create_subsections(subsection_params[:subsections], everything_valid)
      subsections_h = returned[0]
      everything_valid = returned[1]

      if everything_valid
        @recipe.save
        save_subs_n_ings(subsections_h)

        flash[:notice] = 'Recipe was successfully created!'
        flash.keep(:notice)

        render :json => {:location => url_for(recipe_path(@recipe.id))}
      else
        render :json => {:recipe_errors => [@recipe.errors], :subsection_errors => returned[2], :si_errors => returned[3], :ingredient_errors => returned[4]}, :status => 422
      end
    else
      respond_to do |format|
        if @recipe.save
          format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
          format.json { render :show, status: :created, location: @recipe }
        else
          format.html { render :new }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    if request.xhr?
      hours = params.require(:data).permit(:time_h)[:time_h].to_i
      mins = params.require(:data).permit(:time_min)[:time_min].to_i
      @recipe.duration = hours * 60 + mins
      @recipe.description = params.require(:data).permit(:description)[:description]
      @recipe.amount = params.require(:data).permit(:amount)[:amount]
      everything_valid = @recipe.valid?

      returned = update_subsections(subsection_params[:subsections], everything_valid)
      subsections_h = returned[0]
      everything_valid = returned[1]

      if everything_valid
        @recipe.save
        save_subs_n_ings(subsections_h) unless subsections_h.empty?

        flash[:notice] = 'Recipe was successfully updated!'
        flash.keep(:notice)

        render :json => {:location => url_for(recipe_path(@recipe.id))}
      else
        render :json => {:recipe_errors => [@recipe.errors], :subsection_errors => returned[2], :si_errors => returned[3], :ingredient_errors => returned[4]}, :status => 422
      end
    else
      respond_to do |format|
        if @recipe.update(recipe_params)
          format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:data).permit(:name, :description, :amount)
  end

  def subsection_params
    params.require(:data).permit(:subsections => [:title, :ings => [:amount, :unit, :name]])
  end

  def subsection_ingredient_params
    params.require(:data).require(:subsections).require(:subsection_ingredients).permit(:amount, :unit)
  end

  def ingredient_params
    params.require(:data).require(:subsection).require(:subsection_ingredients).permit(:ingredient)
  end

  def set_units
    @units = ["dl", "l", "g", "kg", "tbsp", "tsp", "-", "pcs", "cups"]
  end

  def create_subsections(subsections, everything_valid)
    subsections_h = {}
    subsection_errors = []
    sub_ing_errors = []
    ing_errors = []

    (0..subsections.length-1).each do |i|
      subsection = subsections[i]
      @subsection = Subsection.new
      @subsection.title = subsection[:title]
      everything_valid = false unless @subsection.valid?
      subsection_errors.push @subsection.errors unless @subsection.valid?
      ings = subsection[:ings]
      subsection_h = {}
      subsection_h["s"] = @subsection

      returned = create_sub_ings_n_ings(ings, everything_valid)
      sub_ings_h = returned[0]
      ings_h = returned[1]
      everything_valid = returned[2]
      sub_ing_errors.push(*returned[3])
      ing_errors.push(*returned[4])

      subsection_h["si"] = sub_ings_h
      subsection_h["ings"]= ings_h
      subsections_h[i] = subsection_h
    end

    [subsections_h, everything_valid, subsection_errors, sub_ing_errors, ing_errors]
  end

  def create_sub_ings_n_ings(ings, everything_valid)
    sub_ings_h = {}
    ings_h = {}
    sub_ing_error = []
    ing_error = []

    (0..ings.length-1).each do |j|
      ing = ings[j]
      @subsection_ingredient = SubsectionIngredient.new
      @subsection_ingredient.amount = ing[:amount]
      @subsection_ingredient.unit = ing[:unit]
      @ingredient = Ingredient.new
      @ingredient.name = ing[:name]

      everything_valid = false unless @subsection_ingredient.valid?
      everything_valid = false unless @ingredient.valid?
      sub_ing_error.push(@subsection_ingredient.errors) unless @subsection_ingredient.valid?
      ing_error.push(@ingredient.errors) unless @ingredient.valid?

      sub_ings_h[j] = @subsection_ingredient
      ings_h[j] = @ingredient
    end

    [sub_ings_h, ings_h, everything_valid, sub_ing_error, ing_error]
  end

  def save_subs_n_ings(subsections_h)
    (0..subsections_h.length-1).each do |i|
      @new_subsection = subsections_h[i]["s"]
      @subsection = Subsection.where(recipe_id: @recipe.id, title: @new_subsection.title).first
      if @subsection.nil?
        @subsection = @new_subsection
        @subsection.recipe = @recipe
        @subsection.save
      end
      sub_ings = subsections_h[i]["si"]
      ings = subsections_h[i]["ings"]
      unless ings.nil?
        (0..ings.length-1).each do |j|
          @subsection_ingredient = sub_ings[j]
          @ingredient = Ingredient.find_by_name(ings[j].name)
          unless @ingredient
            @ingredient = ings[j]
            @ingredient.save
          end
          @subsection_ingredient.subsection = @subsection
          @subsection_ingredient.ingredient = @ingredient
          @subsection_ingredient.save
        end
      end
    end
  end

  def update_subsections(subsections, everything_valid)
    subsections_h = {}
    subsection_errors = []
    sub_ing_errors = []
    ing_errors = []

    (0..subsections.length-1).each do |i|
      subsection = subsections[i]
      @subsection = Subsection.new
      @subsection.title = subsection[:title]

      everything_valid = false unless @subsection.valid?
      subsection_errors.push(@subsection.errors) unless @subsection.valid?

      subsection_h = {}
      subsection_h["s"] = @subsection

      ings = subsection[:ings]
      were_there_any_ings = false

      unless ings.nil?
        returned = create_sub_ings_n_ings(ings, everything_valid)

        sub_ings_h = returned[0]
        ings_h = returned[1]
        everything_valid = returned[2]
        sub_ing_errors.push(*returned[3])
        ing_errors.push(*returned[4])

        subsection_h["si"] = sub_ings_h
        subsection_h["ings"]= ings_h
        were_there_any_ings = true;
      end
      subsections_h[i] = subsection_h if were_there_any_ings
    end

    [subsections_h, everything_valid, subsection_errors, sub_ing_errors, ing_errors]
  end

  def ensure_recipe_user_is_current_user
    redirect_to recipe_path(@recipe.id), notice: 'You are not the owner of this recipe' unless @recipe.user==current_user
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :remote => true) do |f| %>

    <div id="errors">
    </div>

    <% if @recipe.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% @recipe.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: 'name'%>
    </div>

    <div class="field">
      <%= f.label :amount %>
      <%= f.number_field :amount, placeholder: 'how many' %> person(s)
    </div>

    <div class="field">
      <%= f.label :duration %>
      <%= f.number_field :time_h, :value => "", placeholder: "hours" %> h
      <%= f.number_field :time_min, :value => "", placeholder: "minutes" %> min
    </div>

    <div id="subsections">

      <div id="subsection1" class="subsection">

        <%= fields_for @recipe.subsections do |s_f| %>
            <div class="field">
              Section <br>
              <%= s_f.text_field :title, :id => "subsection_title1", :class => "subsection_title", :value => '', placeholder: "Section (can be left blank)" %>
            </div>

            <div id="ingredients1" class="ingredients">

              <%= fields_for @recipe.subsection_ingredients do |si_f| %>
                  <%= fields_for @recipe.ingredients do |i_f| %>
                      <div class="row">
                        <div class="col-md-1">
                          <div class="field">
                            Amount <br>
                            <%= si_f.text_field :amount, :value => '', placeholder: 'amount' %>
                          </div>
                        </div>
                        <div class="col-md-1">
                          <div class="field">
                            Unit <br>
                            <%= select("subsection_ingredient", "unit", @units) %>
                          </div>
                        </div>
                        <div class="col-md-1">
                          <div class="field">
                            Ingredient <br>
                            <%= i_f.text_field :name, :value => '', placeholder: 'ingredient' %>
                          </div>
                        </div>
                      </div> <!-- row -->
                  <% end %>
              <% end %>
            </div> <!-- ingredients -->
            <button type="button" id="addI1" class="btn btn-default i">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ingredient
            </button>
        <% end %> <%# subsection%>
      </div> <!-- subsection -->
    </div> <!-- subsections -->
    <button type="button" id="addS" class="btn btn-default">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Section
    </button>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <% if @recipe.new_record? %>
        <div class="actions" , id="create_recipe">
    <% else %>
        <div class="actions" , id="edit_recipe">
    <% end %>
    <%= f.submit class:"btn btn-primary" %>
    </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%#= render 'form', recipe: @recipe %>

<h2><%= @recipe.name %></h2>

<%= form_for(@recipe, :remote => true) do |f| %>

    <div id="errors">
    </div>

    <%= hidden_field_tag :recipe_id, @recipe.id %>
    <div class="field">
      <%= f.label :amount %>
      <%= f.number_field :amount, :value => @recipe.amount %>
    </div>

    <div class="field">
      <%= f.label :duration %>
      <%= f.number_field :time_h, :value => @recipe.duration.divmod(60)[0] %> h
      <%= f.number_field :time_min, :value => @recipe.duration.divmod(60)[1] %> min
    </div>

    <div id="subsections">

      <% @recipe.subsections.each_with_index do |sub, index| %>

          <div id=<%= "subsection#{index+1}" %> class="subsection">
            <%= fields_for @recipe.subsections do |s_f| %>
                <%= hidden_field_tag :subsection_title, sub.title %>

                <h3><%= sub.title %> <%= link_to 'X', sub, method: :delete %></h3>
                <% sub.subsection_ingredients.each do |si| %>
                    <li><%= si %> <%= link_to 'X', si, method: :delete %></li>
                <% end %>

                <div id=<%= "ingredients#{index+1}" %> class="ingredients">

                  <%= fields_for @recipe.subsection_ingredients do |si_f| %>
                      <%= fields_for @recipe.ingredients do |i_f| %>
                      <% end %>
                  <% end %>
                </div> <!-- ingredients -->
                <button type="button" id=<%= "AddI#{index+1}" %> class="btn btn-default i">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ingredient
                </button>
            <% end %> <%# subsection%>
          </div> <!-- subsection -->
      <% end %>
    </div> <!-- subsections -->
    <button type="button" id="addS" class="btn btn-default">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Section
    </button>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, :value => @recipe.description %>
    </div>

    <div class="actions" , id="edit_recipe">
      <%= f.submit class:"btn btn-primary" %>
    </div>

<% end %>

<br>
<%= link_to 'Back to the recipe', @recipe %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<% if @recipes.nil? || @recipes.empty? %>
    No recipes in database.
<% else %>
    <%= pluralize(@recipes.count, "recipe")%> in database.
    <br><br>
    Arrange by <span class="label label-info"><%= link_to 'name', recipes_path(order: "name") %></span> <span class="label label-info"><%= link_to 'last added', recipes_path(order: "added") %></span>
<% end %>

<% @recipes.each do |recipe| %>
    <h3><%= link_to recipe.name, recipe %></h3>
    <%= recipe.amount %> persons, <%= recipe.duration_to_s %> <br><br>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
Section name can be left blank

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>

<div class="row">

  <div class="col-md-6">
    Recipe by: <%= link_to @recipe.user, @recipe.user %> <br><br>
    <%= @recipe.amount %> persons, <%= @recipe.duration_to_s %>
  </div>

  <div class="col-md-6">
    <% @recipe.recipe_categories.each do |rc| %>
        <li><%= link_to rc.category.name, rc.category %> <%= link_to 'X', rc, method: :delete if current_user %></li>
    <% end %>
    <br>
    <%= link_to 'add category', new_recipe_category_path if current_user %>
  </div>
</div>

<h4>Ingredients</h4>


<% @recipe.subsections.each do |s| %>
    <% unless s.title.eql? "" %>
        <strong><%= s.title %></strong> <br>
    <% end %>
    <ul>
      <% s.subsection_ingredients.each do |si| %>
          <li><%= si %></li>
      <% end %>
    </ul>
<% end %>


<h4>Instructions</h4>
<ul>
  <%= @recipe.description %>
</ul>

<% if current_user == @recipe.user %>
    <%= link_to 'Edit', edit_recipe_path(@recipe), class:"btn btn-primary" %> |
    <%= link_to 'Destroy', @recipe, method: :delete, data: {confirm: 'Are you sure?'}, class:'btn btn-danger' %>
<% end %>