config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients, only:[:index, :show, :edit, :update]
  resources :users
  resources :recipes
  resources :recipe_categories, only:[:new, :create, :destroy]
  resources :subsection_ingredients, only:[:destroy]
  resources :subsections, only:[:destroy]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :subsection_ingredients, dependent: :destroy
  has_many :subsections, through: :subsection_ingredients, dependent: :destroy
  has_many :recipes, through: :subsections, dependent: :destroy

  validates :name, length: {minimum: 1, maximum: 30}
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients_with_no_sub_ings = Ingredient.includes(:subsection_ingredients).where(:subsection_ingredients => {:ingredient_id => nil})
    @ingredients_with_no_sub_ings.each { |i| i.delete }

    @ingredients = Ingredient.all
    @ingredients = @ingredients.sort_by { |i| i.name.downcase }
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/1/edit
  def edit
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<% if @ingredients.nil? || @ingredients.empty? %>
    No ingredients in database.
<% else %>
    <%= pluralize(@ingredients.count, "ingredient")%> in database.
    <br><br>
<% end %>

<table class="table table-hover">
  <div class="row">
      <thead>
      <tr>
        <th class="col-md-4">Ingredient</th>
        <th class="col-md-4"># Recipes</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @ingredients.each do |ing| %>
          <tr>
            <td class="col-md-4"><%= link_to ing.name, ing %></td>
            <td class="col-md-4"><span class="badge"><%= ing.recipes.length %></span></td>
            <td></td>
          </tr>
      <% end %>
      </tbody>
  </div>
</table>

app/views/ingredients/show.html.erb
<h2><%= @ingredient.name %></h2>

<ul>
  <% @ingredient.recipes.each do |recipe| %>
      <li><%= link_to recipe.name, recipe %></li>
  <% end %>
</ul>

<% if current_user %>
    <%= link_to 'Edit', edit_ingredient_path(@ingredient), class: "btn btn-primary" %>
    <%= link_to 'Destroy', @ingredient, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
<% end %>