config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients, only:[:index, :show, :edit, :update]
  resources :users
  resources :recipes
  resources :recipe_categories, only:[:new, :create, :destroy]
  resources :subsection_ingredients, only:[:destroy]
  resources :subsections, only:[:destroy]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, through: :recipe_categories
  has_many :recipe_categories

  validates :name, length: {minimum: 3, maximum: 30}, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @categories = @categories.sort_by { |c| c.name.downcase }
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.name = @category.name.downcase

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        @category.name = @category.name.downcase
        @category.save
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
      <li><%= link_to category.name, category %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<ul>
  <% @category.recipes.each do |recipe| %>
      <li><%= link_to recipe.name, recipe %></li>
  <% end %>
</ul>

<% if current_user %>
    <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-primary" %>
    <%= link_to 'Destroy', @category, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
<% end %>